module:
  mounts:
    - source: blox
      target: layouts/partials/blox/community/
      includeFiles: '**.html'
    - source: blox
      target: assets/dist/community/blox/
      includeFiles: '**.css'
    - source: blox/header
      target: layouts/partials/blox/community/header/
      includeFiles: '**.html'
    - source: blox/helpers
      target: layouts/partials/blox/community/helpers/
      includeFiles: '**.html'
    - source: blox
      target: layouts/partials/hbx/blocks/
      includeFiles: '**.html'